### ISSUE TITLE
AppImage don't work

### ISSUE THREAD

**Issue by als-creator** [ivan-hc/OBS-Studio-appimage#12]
OS: Arch Linux (x86_64)
Kernel: Linux 6.10.4-x64v2-xanmod1-1-x64v2
DE: Xfce4 4.18
Perché nessuna delle tue immagini viene pubblicata?  Ho provato a scaricare diverse immagini, nessuna è stata avviata, l'immagine è contrassegnata come eseguibile, tutte le altre immagini che ho scaricato da appimagehub funzionano bene per me, ma molte di esse sono già obsolete

**Comment by ivan-hc** [comment]
try to run it from the terminal and read the error messages

I'm sure you have an issue with `fusermount`

my AppImages are ment to work without the needing of the obsolete libfuse2 library

**Comment by ivan-hc** [comment]
comunque, essendo Arch Linux, tu hai sia `fusermount` che `fusermount3`, qualora il tuo `fusermount` fosse solo un collegamento a `fusermount3`, come succede in Debian, l'AppImage dovrebbe avviarsi.

È un workaround, ma che verrà presto risolto. Sto aspettando gli sviluppatori di AppImage che forniscano `appimagetool` aggiornato con le nuove modifiche. Il problema non dovrà più sussistere.

**Comment by als-creator** [comment]
> try to run it from the terminal and read the error messages
> 
> I'm sure you have an issue with `fusermount`
> 
> my AppImages are ment to work without the needing of the obsolete libfuse2 library
> 
> PS: ma sei italiano? Pensavo fosse google translate che aveva tradotto la pagina in automatico

QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: qt5ct-style, Windows, Fusion
execv error: No such file or directory

Utilizzo un traduttore per l'italiano

**Comment by ivan-hc** [comment]
uhm... obs-studio is a QT app, what happens if you install `qt5ct` and `kvantum`/`kvantum-qt5` from "pacman"?

**Comment by als-creator** [comment]
Non avevo Quantum installato su un altro PC, ora ho Quantum, ma non mi piace usarlo, c'è un'opzione per eseguire immagini senza Quantum?

**Comment by ivan-hc** [comment]
You are doing a question that is the same as asking for using a gtk4/libadwaita app without gtk4/adwaita.

It is a toolkit problem, not of the Appimage.

To integrate QT apps on a GTK environment is an issue from decades, since QT and GTK were built.

https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications

Kvantum (:+1: ) and adwaita-qt (:-1: ) are what can help you integrate QT apps with the look of your GTK environment.

In my use case, I have XFCE4 that is GTK-based too, and to solved by installing kvantum and qt5ct, on Debian, and I have followed the same guide from arch linux wiki I have just linked above.

This is the result:

![Istantanea_2024-08-14_21-49-01](https://github.com/user-attachments/assets/09a8edbb-3f0e-4a80-bfb0-296ca67b89df)

I use KvMojave among Kvantum themes, it is the only one that works as it should and it is ways better than adwaita-qt.

I have done nothing with qt5ct but used the defaults, maybe the only change is this

![Istantanea_2024-08-14_21-50-50](https://github.com/user-attachments/assets/648a9197-64ee-46d6-aa15-66f39701d4e0)

then save and close.

**Comment by ivan-hc** [comment]
And if it can help you, I also added this to my /etc/environment file
```
GTK_THEME=Adwaita-dark
QT_FONT_DPI=96
GSK_RENDERER=gl
```
the one in the middle is to keep font of QT apps with the same sizes of the ones of xfce apps, may them be system apps or AppImages

the other two are for GTK/Libadwaita apps:

1. because libadwaita apps keep use a different theme from the one I use in XFCE
3. because some libadwaita apps have some glitches for me, because I have an old Nvidia

and libadwaita is the real evil for us, XFCE users

**Comment by ivan-hc** [comment]
in the meantime I'm including missing dependences in the AppImage

**Comment by ivan-hc** [comment]
the new AppImage will be ready in minutes, if it still does not work, please reopen this issue

**Comment by als-creator** [comment]
Ora tutto inizia per me senza Quantum, ma esiste un gestore di pacchetti già pronto per appimage in archlinux?

**Comment by ivan-hc** [comment]
there are several, I have the mine

https://github.com/ivan-hc/AM

**Comment by ivan-hc** [comment]
Released https://github.com/ivan-hc/AM/releases/tag/7.7
